# Generated by Django 4.0.3 on 2022-04-03 17:57

from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spr_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Справочник: "Категории товара"',
            },
        ),
        migrations.CreateModel(
            name='spr_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('type_company', models.IntegerField(choices=[(0, 'Юридическое лицо'), (1, 'Обособленное подразделение'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Вид юр.лица')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name_full', models.CharField(blank=True, default='', max_length=250, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, verbose_name='КПП')),
                ('addres_u', models.CharField(blank=True, default='', max_length=250, verbose_name='Юридический адрес')),
                ('addres_f', models.CharField(blank=True, default='', max_length=250, verbose_name='Фактический адрес')),
                ('addres_p', models.CharField(blank=True, default='', max_length=250, verbose_name='Почтовый адрес')),
                ('pref', models.CharField(max_length=2, verbose_name='Префикс документов')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Справочник: "Организации"',
            },
        ),
        migrations.CreateModel(
            name='spr_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('guest_min', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Минимальное')),
                ('guest_max', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Максимальное')),
                ('date_vvoda_start', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('date_vvoda_stop', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('kol_min', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Минимальное')),
                ('kol_max', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Максимальное')),
                ('summa_min', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Минимальное')),
                ('summa_max', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Максимальное')),
                ('d1', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('d2', models.BooleanField(default=False, verbose_name='Вторник')),
                ('d3', models.BooleanField(default=False, verbose_name='Среда')),
                ('d4', models.BooleanField(default=False, verbose_name='Четверг')),
                ('d5', models.BooleanField(default=False, verbose_name='Пятница')),
                ('d6', models.BooleanField(default=False, verbose_name='Суббота')),
                ('d7', models.BooleanField(default=False, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Условие применение',
                'verbose_name_plural': 'Справочник: "Условия примнения скидок\\наценок"',
            },
        ),
        migrations.CreateModel(
            name='spr_conditions_tabl_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Условия (Категория)',
                'verbose_name_plural': 'Условия (Категория)',
            },
        ),
        migrations.CreateModel(
            name='spr_discont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('allcategories', models.BooleanField(default=False, verbose_name='Для всех категорий')),
                ('arbitraryvalue', models.BooleanField(default=False, verbose_name='Произвольное значение')),
                ('enable', models.BooleanField(default=True, verbose_name='вкл.')),
                ('manually', models.BooleanField(default=False, verbose_name='Ручная')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('type_discount', models.IntegerField(choices=[(0, 'Скидка (%)'), (1, 'Скидка (сумма)'), (2, 'Наценка (%)'), (3, 'Наценка (сумма)')], default=0, verbose_name='Вид скидки/наценки')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки',
                'verbose_name_plural': 'Справочник: "СкидкиНаценки"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_tabl_spr_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Категория)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Категории)"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_tabl_spr_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Условия применения)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Условия применения)"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_tabl_spr_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Подразделение)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Подразделения)"',
            },
        ),
        migrations.CreateModel(
            name='spr_doljnosty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Справочник: "Должности персонала"',
            },
        ),
        migrations.CreateModel(
            name='spr_fizlitso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
                ('familiya', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('imy', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество')),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to=main.models.directory_path_image, verbose_name='Фото')),
                ('pol', models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], default=0, verbose_name='Пол')),
                ('DateOfBirth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Справочник: "Физические лица"',
            },
        ),
        migrations.CreateModel(
            name='spr_grprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа печати',
                'verbose_name_plural': 'Справочник: "Группы печати"',
            },
        ),
        migrations.CreateModel(
            name='spr_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('group', models.BooleanField(default=False, verbose_name='Группа')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name_full', models.CharField(max_length=150, verbose_name='Полное наименование')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('ves', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вес (гр.)')),
                ('time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время приготовления (мин)')),
                ('calories', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ККал')),
                ('belki', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Белки')),
                ('jiry', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Жири')),
                ('uglevody', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Углеводы')),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to=main.models.directory_path_image, verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='сортировка')),
                ('izbran', models.BooleanField(default=False, verbose_name='Избранный')),
                ('vesovoy', models.BooleanField(default=False, verbose_name='Весовой')),
                ('zaprosprice', models.BooleanField(default=False, verbose_name='Запрашивать цену')),
                ('podarok', models.BooleanField(default=False, verbose_name='Признак "Подарок"')),
                ('zapretruchnogovybora', models.BooleanField(default=False, verbose_name='Запрет ручного выбора')),
                ('kodPodbora', models.CharField(blank=True, default='', max_length=6, verbose_name='Наименование')),
                ('name_kuhny', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование для кухни')),
                ('separate', models.BooleanField(default=False, verbose_name='Отдельный')),
            ],
            options={
                'verbose_name': 'Состав меню',
                'verbose_name_plural': 'Справочник: "Состав меню"',
            },
        ),
        migrations.CreateModel(
            name='spr_menu_tabl_spr_modificators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Меню (модификатор)',
                'verbose_name_plural': 'Справочник: "Меню (модификаторы)"',
            },
        ),
        migrations.CreateModel(
            name='spr_modificators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('group', models.BooleanField(default=False, verbose_name='Группа')),
                ('min_quantity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Мин. кол.')),
                ('max_quantity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Макс. кол.')),
                ('bezDubley', models.BooleanField(default=False, verbose_name='Без дублей')),
                ('pr_nomenklatura', models.BooleanField(default=False, verbose_name='Признак номенклатура')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Справочник: "Модификаторы"',
            },
        ),
        migrations.CreateModel(
            name='spr_nomenklatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('group', models.BooleanField(default=False, verbose_name='Подгруппа')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('alco', models.BooleanField(default=False, verbose_name='Алкогольная продукция')),
                ('marked', models.BooleanField(default=False, verbose_name='Маркируемый')),
                ('type_nomenklatura', models.IntegerField(blank=True, choices=[(0, 'Товар'), (1, 'Услуга')], default=0, null=True, verbose_name='Вид номенклатуры')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Справочник: "Номенклатуры"',
            },
        ),
        migrations.CreateModel(
            name='spr_nomenklatura_barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('barcode', models.CharField(max_length=13, verbose_name='Штрих-код')),
            ],
            options={
                'verbose_name': 'Штрих-код',
                'verbose_name_plural': 'Справочник: "Штрих-коды единиц измерения"',
            },
        ),
        migrations.CreateModel(
            name='spr_nomenklatura_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('koef', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Коеф.')),
            ],
            options={
                'verbose_name': 'Единицы номенклатуры',
                'verbose_name_plural': 'Справочник: "Единицы номенклатуры"',
            },
        ),
        migrations.CreateModel(
            name='spr_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Справочник: "Подразделения"',
            },
        ),
        migrations.CreateModel(
            name='spr_object_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Псевдоним')),
                ('barcode', models.CharField(blank=True, default='', max_length=30, verbose_name='Штрих-код')),
                ('password', models.CharField(blank=True, default='', max_length=30, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь POS',
                'verbose_name_plural': 'Справочник: "Пользователи POS"',
            },
        ),
        migrations.CreateModel(
            name='spr_otdely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Справочник: "Отделы"',
            },
        ),
        migrations.CreateModel(
            name='spr_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('imageFile', models.ImageField(upload_to=main.models.directory_path_image, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Справочник: "Картинки"',
            },
        ),
        migrations.CreateModel(
            name='spr_priznakdelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('b_authorization', models.BooleanField(default=False, verbose_name='Требуется авторизация')),
                ('type_delete', models.IntegerField(choices=[(0, 'Без списания'), (1, 'За счет организации'), (2, 'За счет сотрудника')], default=0, verbose_name='Вид удаления')),
            ],
            options={
                'verbose_name': 'Признак удаления',
                'verbose_name_plural': 'Справочник: "Признаки удаления"',
            },
        ),
        migrations.CreateModel(
            name='spr_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('type_role', models.IntegerField(choices=[(0, 'Добавление'), (1, 'Исключение')], default=0, verbose_name='Тип')),
                ('p_smena', models.BooleanField(default=False, verbose_name='Открытие / закрытие смены')),
                ('p_sale', models.BooleanField(default=False, verbose_name='Регистрация продаж')),
                ('p_menu', models.BooleanField(default=False, verbose_name='меню')),
                ('p_obmen', models.BooleanField(default=False, verbose_name='Загрузка с портала обновлений данных.')),
                ('p_report', models.BooleanField(default=False, verbose_name='Отчеты рабочего места')),
                ('p_setting', models.BooleanField(default=False, verbose_name='Установка РМ')),
                ('p_exit', models.BooleanField(default=False, verbose_name='Выход из программы')),
                ('p_zaprosSave', models.BooleanField(default=False, verbose_name='Запрос записи изменений')),
                ('p_return', models.BooleanField(default=False, verbose_name='Возврат')),
                ('p_stoplist', models.BooleanField(default=False, verbose_name='Стоп-лист')),
                ('p_print_tovchek', models.BooleanField(default=False, verbose_name='Печать товарного чека')),
                ('p_print_shet', models.BooleanField(default=False, verbose_name='Печать предчека')),
                ('p_statiySpisaniy', models.BooleanField(default=False, verbose_name='Потверждение статей списания')),
                ('p_onlyYourOrders', models.BooleanField(default=False, verbose_name='Работа только со своими заказами')),
                ('p_removeBlock', models.BooleanField(default=False, verbose_name='Снимать блок с заказа')),
                ('p_opentara', models.BooleanField(default=False, verbose_name='Вскрытие тары')),
            ],
            options={
                'verbose_name': 'Права доступа',
                'verbose_name_plural': 'Справочник: "Права доступа"',
            },
        ),
        migrations.CreateModel(
            name='spr_statiyzatrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статья затрат',
                'verbose_name_plural': 'Справочник: "Статьи затрат"',
            },
        ),
        migrations.CreateModel(
            name='spr_stavkands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Наименование')),
                ('stavka', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ставка.')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Справочник: "Ставки НДС"',
            },
        ),
        migrations.CreateModel(
            name='spr_typemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Справочник: "Типы меню"',
            },
        ),
        migrations.CreateModel(
            name='spr_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('kod', models.CharField(blank=True, default='', max_length=4, verbose_name='ОКЕА')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Справочник: "Классификатор единиц измерения"',
            },
        ),
        migrations.CreateModel(
            name='spr_variantoplaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('type_oplaty', models.IntegerField(choices=[(0, 'Наличными'), (1, 'Безначичными'), (2, 'Без выручки')], default=0, verbose_name='Вид оплаты')),
            ],
            options={
                'verbose_name': 'Вариант оплаты',
                'verbose_name_plural': 'Справочник: "Варианты оплаты"',
            },
        ),
        migrations.CreateModel(
            name='spr_zaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Справочник: "Залы"',
            },
        ),
    ]
