# Generated by Django 4.0.3 on 2022-04-03 12:38

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0003_spr_doljnosty_spr_fizlitso_spr_nomenklatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_fizlitso',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.directory_path_image, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='spr_stavkands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Наименование')),
                ('stavka', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ставка.')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Справочник: "Ставки НДС"',
            },
        ),
        migrations.CreateModel(
            name='spr_priznakdelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('b_authorization', models.BooleanField(default=False, verbose_name='Требуется авторизация')),
                ('type_delete', models.IntegerField(choices=[(0, 'Без списания'), (1, 'За счет организации'), (2, 'За счет сотрудника')], default=0, verbose_name='Вид удаления')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Признак удаления',
                'verbose_name_plural': 'Справочник: "Признаки удаления"',
            },
        ),
        migrations.CreateModel(
            name='spr_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('imageFile', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Справочник: "Картинки"',
            },
        ),
        migrations.CreateModel(
            name='spr_otdely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер отдела')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Справочник: "Отделы"',
            },
        ),
        migrations.CreateModel(
            name='spr_grprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Группа печати',
                'verbose_name_plural': 'Справочник: "Группы печати"',
            },
        ),
        migrations.CreateModel(
            name='spr_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Справочник: "Категории товара"',
            },
        ),
    ]
