# Generated by Django 4.0.3 on 2022-04-03 12:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_spr_fizlitso_imagefile_spr_stavkands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_pictures',
            name='imageFile',
            field=models.ImageField(upload_to=main.models.directory_path_image, verbose_name='Картинка'),
        ),
    ]
