# Generated by Django 4.0.3 on 2022-04-03 14:38

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0006_spr_nomenklatura_barcode_spr_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='spr_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Условие применение',
                'verbose_name_plural': 'Справочник: "Условия примнения скидок\\наценок"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('allcategories', models.BooleanField(default=False, verbose_name='Для всех категорий')),
                ('arbitraryvalue', models.BooleanField(default=False, verbose_name='Произвольное значение')),
                ('enable', models.BooleanField(default=True, verbose_name='вкл.')),
                ('manually', models.BooleanField(default=False, verbose_name='Ручная')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('type_discount', models.IntegerField(choices=[(0, 'Скидка (%)'), (1, 'Скидка (сумма)'), (2, 'Наценка (%)'), (3, 'Наценка (сумма)')], default=0, verbose_name='Вид скидки/наценки')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Значение')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки',
                'verbose_name_plural': 'Справочник: "СкидкиНаценки"',
            },
        ),
        migrations.AlterField(
            model_name='spr_menu',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.directory_path_image, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='spr_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('group', models.BooleanField(default=False, verbose_name='Группа')),
                ('min_quantity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Мин. кол.')),
                ('max_quantity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Макс. кол.')),
                ('bezDubley', models.BooleanField(default=False, verbose_name='Без дублей')),
                ('pr_nomenklatura', models.BooleanField(default=False, verbose_name='Признак номенклатура')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена')),
                ('nomenklatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.spr_nomenklatura', verbose_name='Номенклатура')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.spr_mod', verbose_name='Подгруппа')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.spr_nomenklatura_units', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Справочник: "Модификаторы"',
            },
        ),
        migrations.CreateModel(
            name='spr_menu_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_mod', verbose_name='Модификатор')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_menu', verbose_name='Позиция меню')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Меню (модификатор)',
                'verbose_name_plural': 'Справочник: "Меню (модификаторы)"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_discont', verbose_name='Скидка/Наценка')),
                ('podrazdelenie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_object', verbose_name='Подразделение')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Подразделение)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Подразделения)"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_conditions', verbose_name='Условие')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_discont', verbose_name='Скидка/Наценка')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Условия применения)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Условия применения)"',
            },
        ),
        migrations.CreateModel(
            name='spr_discont_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Значение')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_categories', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_discont', verbose_name='Скидка/Наценка')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Скидка\\Наценки (Категория)',
                'verbose_name_plural': 'Справочник: "Скидка\\Наценки (Категории)"',
            },
        ),
    ]
