# Generated by Django 4.0.3 on 2022-04-03 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0009_spr_conditions_d1_spr_conditions_d2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='spr_conditions_tablcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_update', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_categories', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.spr_conditions', verbose_name='Условия примнения скидок\\наценок')),
                ('reg_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reg_global', verbose_name='Global ID')),
            ],
            options={
                'verbose_name': 'Условия (Категория)',
                'verbose_name_plural': 'Условия (Категория)',
            },
        ),
    ]
