# Generated by Django 4.0.3 on 2022-04-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0011_rename_spr_conditions_tablcategories_spr_conditions_tabl_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spr_discont_tabl_categories',
            new_name='spr_discont_tabl_spr_categories',
        ),
        migrations.RenameModel(
            old_name='spr_discont_tabl_conditions',
            new_name='spr_discont_tabl_spr_conditions',
        ),
        migrations.RenameModel(
            old_name='spr_discont_tabl_object',
            new_name='spr_discont_tabl_spr_object',
        ),
        migrations.RenameModel(
            old_name='spr_menu_mod',
            new_name='spr_menu_tabl_spr_mod',
        ),
    ]
